services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devs-sql-server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong@Password123}
      - MSSQL_PID=Developer
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
    driver: local
